package org.com.smu.societe;

import android.content.Context;
import android.graphics.Canvas;
import android.view.View;
/**
* ARScene 클래스는 카메라 프리뷰에 오버레이될 전체적인 증강현실 뷰를 
* 포함하는 클래스임. 
* DataInformView가 표시될 마커들을 포함하는 뷰인데 센서값이 변할때마다
* postInvalidate()를 통해 계속해서 그려지게 됨
* Generated by StarUML(tm) Java Add-In
*
* @Project  Societe
* @File  	ARScene.java
* @Date  	2010-10-10
* @Author  	ACE
*/
public class ARScene extends View {
	ARView app;

	public ARScene(Context context) {
		super(context);

		try {
			app = (ARView) context;

			//에러발생 처리
			app.killOnError();
		} catch (Exception ex) {
			app.doError(ex);
		}
	}

	/**
	  * 전체적인 증강현실에 관련된 뷰를 그려주는 역할을 하는 함수임
	  * DataInformView 의 크기와 그려질 Canvas 를 set
	  * DataInformView 가 초기화 되지 않았을 경우에 초기화 후 그려줌
	  * 
	  * @param canvas 증강현실에 관련된 뷰를 그리는 베이스
	  * @exception Exception 뷰를 생성하는 동안 예외발생
	  */
	@Override
	protected void onDraw(Canvas canvas) {
		//전체적인 증강현실에 관련된 뷰를 그려주는 역할을 하는 함수임
		try {

			//에러처리
			app.killOnError();

			//DataInformView 의 크기와 그려질 Canvas 를 set
			ARView.dWindow.setWidth(canvas.getWidth());
			ARView.dWindow.setHeight(canvas.getHeight());
			ARView.dWindow.setCanvas(canvas);

			//DataInformView 가 초기화 되지 않았을 경우에 초기화
			if (!ARView.view.isInited()) {
				ARView.view.init(ARView.dWindow.getWidth(),
						ARView.dWindow.getHeight());
			}		

			//DataInformView 를 그려줌
			ARView.view.draw(ARView.dWindow);
		} catch (Exception ex) {
			app.doError(ex);
		}
	}
}
